apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "6s"
        autoscaling.knative.dev/scale-down-delay: "1s"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1s"
        autoscaling.knative.dev/scale-to-zero-grace-period: "1s"
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
